export const FETCH_CART_ITEM = "FETCH_CART_ITEM";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const UPDATE_QUANTITY = "UPDATE_QUANTITY";
export const UPDATE_QUANTITY_OPTIMISTIC = "UPDATE_QUANTITY_OPTIMISTIC";
export const REVERT_QUANTITY = "REVERT_QUANTITY";
export const CART_COUNT = "CART_COUNT";
